services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Tienvx\Bundle\MbtExamplesBundle\:
        resource: '../../*'
        exclude: '../../Resources/'
